import Head from "next/head";

import AppLayout from "@/components/Layout/AppLayout";
import NotesData from "@/components/NotesData";
import { api } from "@/utils/api";
import { useUser } from "@clerk/nextjs";
import { Inter as FontSans } from "next/font/google";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import {BiArchiveIn} from 'react-icons/bi'


export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export default function Home() {

  const user = useUser();

  const router = useRouter();

  console.log(router, 'router');
  const { data: notes, isLoading, isError } = api.note.getNotes.useQuery(
    
  )



  const [pinnedNotes, setPinnedNotes] = useState(notes?.filter((x) => x.pinned && !x.archived) ?? [])
  const [unpinned, setUnpinnedNotes] = useState(notes?.filter((x) => !x.pinned && !x.archived) ?? [])
  console.log(pinnedNotes, 'pinnedNotes')

  useEffect(() => {
    if (notes) {
      setPinnedNotes(notes.filter((x) => x.archived && x.pinned))
      setUnpinnedNotes(notes?.filter((x) => !x.pinned && x.archived))
    }
  }, [notes])


  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppLayout>
        <div className='w-full '>

          {
            notes && 
            <div className='mt-4'>
              <h2 className='text-sm font-medium uppercase text-gray-500 my-4'>
                {pinnedNotes.length > 0 && 'Pinned'}
              </h2>
              <NotesData notes={pinnedNotes} />
              <h2 className='text-sm font-medium uppercase text-gray-500 my-4'>
                {pinnedNotes.length > 0 && 'Other'}
              </h2>
              <NotesData notes={unpinned} />
            </div>
          }
          {
            (pinnedNotes?.length + unpinned.length) === 0 && 
            <div className="max-w-lg mx-auto w-full flex flex-col items-center justify-center text-center  text-gray-300 text-3xl font-medium gap-10">
              Your Archived Notes will come here
              <BiArchiveIn  className="w-20 h-20 font-thin "/>
            </div>

          }
        </div>
      </AppLayout>

    </>
  );
}
